### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by sbp** [sbp/saxo#71]
Somebody reports an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/saxo", line 13, in <module>
    main()
  File "/usr/local/bin/saxo", line 10, in main
    saxo.script(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/saxo/core.py", line 343, in script
    main(argv, version)
  File "/usr/local/lib/python3.4/dist-packages/saxo/script.py", line 559, in main
    code = action.names[args.action](args)
  File "/usr/local/lib/python3.4/dist-packages/saxo/script.py", line 141, in create
    from . import create
  File "/usr/local/lib/python3.4/dist-packages/saxo/create.py", line 11, in <module>
    from .saxo import path as saxo_path
  File "/usr/local/lib/python3.4/dist-packages/saxo/saxo.py", line 4, in <module>
    from core import *
ImportError: No module named 'core'
```

And getting them to change to `from .core import *` worked, so presumably the fix is the usual "Save PEP 3122!" style. But why hasn't this error been found before?

**Comment by sbp** [comment]
Fixed anyway in 11cedb8.
